name: Generate contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2324D6E8&color_dots=%23E8EEF5,%23C4B5FD,%239A6BFF,%23419BFF,%232FE6A1
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2324D6E8&color_dots=%23111D2D,%23213A58,%23704ED6,%2329A9D6,%232FE6A1

      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
